/*
Concrete grammar.
State names can be standard identifiers, or arbitrary quoted strings.
States are allowed to be empty. The execution will panic if it doesn't find a fitting selector.
Pass-through states are allowed; they are equivalent to a single [!]-selected branch.
There are different options for branch termination:
- "accept", "reject": terminate with the selected state
- id: jump to the specified state
- nothing: jump to the current state
*/

id_start = { 'a'..'z' | 'A'..'Z' | "_" }
id_continue = { id_start | '0'..'9' }
id = @{ !(keyword_accept ~ !id_continue) ~
        !(keyword_reject ~ !id_continue) ~
        id_start ~ (id_continue)*
    | "\"" ~ ascii_printable+ ~ "\""
 }

keyword_accept = { "accept" }
keyword_reject = { "reject" }

char = @{ "'" ~ char_inner ~ "'" }
char_inner = @{ "x" ~ hexdigit ~ hexdigit | ascii_printable }
hexdigit = { '0'..'9' | 'a'..'f' }

statedesc = { id ~ "{" ~ (branch_body | branch*) ~ "}" }
branch = { selector ~ branch_body }
branch_body = { primitive* ~ call? }
call = { id | keyword_accept | keyword_reject }
selector = { "[" ~ char ~ ("," ~ char)* ~ "]" | "[!]" }
primitive = { "<" | ">" | "#" ~ char }

machine = { SOI ~ statedesc* ~ EOI }

ascii_printable = { '\u{20}'..'\u{7e}' }
WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
